print('[INFO] Checking entity2id number of lines')
entity2IdFile = open('/home/sangameswaran/DKRL/entity2id.txt', 'r')
entity_num_lines = sum(1 for line in entity2IdFile)
print('[INFO] entity2id number of entities: '+ str(entity_num_lines))
print('[INFO] checking entity2vec')
entity2vec_file = open('/home/sangameswaran/DKRL/entity2vec.bern', 'r')
entity2vec_lines = sum(1 for line in entity2vec_file)
print('[INFO] Entity to vec (bern file) :' + str(entity2vec_lines))
print('[INFO] Checking Relation2id file')
relation2id_file = open('/home/sangameswaran/DKRL/relation2id.txt', 'r')
relation2id_lines = sum(1 for line in relation2id_file)
print('[INFO] Relation2id Number of relations: '+ str(relation2id_lines))
print('[INFO] Checking Relation2id.bern file')
relation2vec_file = open('/home/sangameswaran/DKRL/relation2vec.bern', 'r')
relation2vec_lines = sum(1 for line in relation2vec_file)
print('[INFO] Relation2vec No of vectors: ' + str(relation2vec_lines))
word2vec_lines = sum(1 for line in open('/home/sangameswaran/DKRL/word2id.txt'))
print(word2vec_lines)
